# 01 Ramom Forest & KNN
random forest의 hyperparameter를 설정해봅시다. 준이가 원하는 hyperparameter를 하나 골라봅시다. hyperparameter의 값은 5종류로 설정해봅시다. 그럼 서로 다른 hyperparameter를 가진 random forest 5개가 만들어지겠죠?
knn의 hyperparameter k 값을 각각 다르게 5개의 서로 다른 knn을 만들어봅시다.
이 10개의 모델 중 titanic dataset의 생존 예측 성능이 가장 좋은 건 누구인가요? (전처리 하는 거 잊지 마세요!)

참조 : https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
df['Sex']

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [4]:
mapping = {'male':0, 'female':1}

In [5]:
df['Sex'].map(mapping)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [6]:
df['Sex'] = df['Sex'].map(mapping)

In [7]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [8]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mode()[0])

In [10]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [11]:
embarked_mapping = {'Q':0, 'S':1, 'C':2}
df['Embarked'].map(embarked_mapping)

0      1
1      2
2      1
3      1
4      1
      ..
886    1
887    1
888    1
889    2
890    0
Name: Embarked, Length: 891, dtype: int64

In [12]:
df['Embarked'] = df['Embarked'].map(embarked_mapping)

In [13]:
import matplotlib.pyplot as plt

In [14]:
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)

In [15]:
IQR = Q3-Q1

In [16]:
whisker_width = 1.5
lower_whisker = Q1-whisker_width*IQR
upper_whisker = Q3+whisker_width*IQR

In [17]:
df['Fare'] < lower_whisker

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [18]:
df['Fare'] > upper_whisker

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [19]:
(df['Fare'] < lower_whisker) | (df['Fare'] > upper_whisker)

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [20]:
df[(df['Fare'] < lower_whisker) | (df['Fare'] > upper_whisker)]

     Survived  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
1           1       1    1  38.0      1      0   71.2833         2
27          0       1    0  19.0      3      2  263.0000         1
31          1       1    1  24.0      1      0  146.5208         2
34          0       1    0  28.0      1      0   82.1708         2
52          1       1    1  49.0      1      0   76.7292         2
..        ...     ...  ...   ...    ...    ...       ...       ...
846         0       3    0  24.0      8      2   69.5500         1
849         1       1    1  24.0      1      0   89.1042         2
856         1       1    1  45.0      1      1  164.8667         1
863         0       3    1  24.0      8      2   69.5500         1
879         1       1    1  56.0      0      1   83.1583         2

[116 rows x 8 columns]

In [21]:
df[(df['Fare'] > lower_whisker) & (df['Fare'] < upper_whisker)]

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    0  22.0      1      0   7.2500         1
2           1       3    1  26.0      0      0   7.9250         1
3           1       1    1  35.0      1      0  53.1000         1
4           0       3    0  35.0      0      0   8.0500         1
5           0       3    0  24.0      0      0   8.4583         0
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    0  27.0      0      0  13.0000         1
887         1       1    1  19.0      0      0  30.0000         1
888         0       3    1  24.0      1      2  23.4500         1
889         1       1    0  26.0      0      0  30.0000         2
890         0       3    0  32.0      0      0   7.7500         0

[775 rows x 8 columns]

In [22]:
df = df[(df['Fare'] > lower_whisker) & (df['Fare'] < upper_whisker)]

In [23]:
df.reset_index()

     index  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0        0         0       3    0  22.0      1      0   7.2500         1
1        2         1       3    1  26.0      0      0   7.9250         1
2        3         1       1    1  35.0      1      0  53.1000         1
3        4         0       3    0  35.0      0      0   8.0500         1
4        5         0       3    0  24.0      0      0   8.4583         0
..     ...       ...     ...  ...   ...    ...    ...      ...       ...
770    886         0       2    0  27.0      0      0  13.0000         1
771    887         1       1    1  19.0      0      0  30.0000         1
772    888         0       3    1  24.0      1      2  23.4500         1
773    889         1       1    0  26.0      0      0  30.0000         2
774    890         0       3    0  32.0      0      0   7.7500         0

[775 rows x 9 columns]

In [24]:
df = df.reset_index()

In [25]:
df = df.iloc[:,1:]

In [26]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [27]:
scaler = StandardScaler()

In [28]:
np.array(df['Fare'])

array([ 7.25  ,  7.925 , 53.1   ,  8.05  ,  8.4583, 51.8625, 21.075 ,
       11.1333, 30.0708, 16.7   , 26.55  ,  8.05  , 31.275 ,  7.8542,
       16.    , 29.125 , 13.    , 18.    ,  7.225 , 26.    , 13.    ,
        8.0292, 35.5   , 21.075 , 31.3875,  7.225 ,  7.8792,  7.8958,
       27.7208,  7.75  , 10.5   , 52.    ,  7.2292,  8.05  , 18.    ,
       11.2417,  9.475 , 21.    ,  7.8958, 41.5792,  7.8792,  8.05  ,
       15.5   ,  7.75  , 21.6792, 17.8   , 39.6875,  7.8   , 26.    ,
       61.9792, 35.5   , 10.5   ,  7.2292, 27.75  , 46.9   ,  7.2292,
       27.9   , 27.7208, 15.2458, 10.5   ,  8.1583,  7.925 ,  8.6625,
       10.5   , 46.9   , 14.4542, 56.4958,  7.65  ,  7.8958,  8.05  ,
       29.    , 12.475 ,  9.    ,  9.5   ,  7.7875, 47.1   , 10.5   ,
       15.85  , 34.375 ,  8.05  ,  8.05  ,  8.05  ,  7.8542, 61.175 ,
       20.575 ,  7.25  ,  8.05  , 34.6542, 63.3583, 23.    , 26.    ,
        7.8958,  7.8958,  8.6542,  7.925 ,  7.8958,  7.65  ,  7.775 ,
        7.8958, 24.15  , 52.    , 14.4542,  8.05  ,  9.825 , 14.4583,
        7.925 ,  7.75  , 21.    , 31.275 ,  8.05  , 30.0708, 13.    ,
       11.2417,  7.75  ,  7.1417, 22.3583,  6.975 ,  7.8958,  7.05  ,
       14.5   , 26.    , 13.    , 15.0458, 26.2833, 53.1   ,  9.2167,
       15.2458,  7.75  , 15.85  ,  6.75  , 11.5   , 36.75  ,  7.7958,
       34.375 , 26.    , 13.    , 12.525 ,  8.05  , 14.5   ,  7.3125,
       61.3792,  7.7333,  8.05  ,  8.6625, 16.1   , 15.75  ,  7.775 ,
        8.6625, 39.6875, 20.525 , 55.    , 27.9   , 25.925 , 56.4958,
       33.5   , 29.125 , 11.1333,  7.925 , 30.6958,  7.8542, 25.4667,
       28.7125, 13.    ,  0.    , 15.05  , 31.3875, 39.    , 22.025 ,
       50.    , 15.5   , 26.55  , 15.5   ,  7.8958, 13.    , 13.    ,
        7.8542, 26.    , 27.7208,  7.75  ,  8.4042,  7.75  , 13.    ,
        9.5   ,  6.4958,  7.225 ,  8.05  , 10.4625, 15.85  , 18.7875,
        7.75  , 31.    ,  7.05  , 21.    ,  7.25  , 13.    ,  7.75  ,
        7.925 , 27.    , 10.5   ,  8.05  , 13.    ,  8.05  ,  7.8958,
        9.35  , 10.5   ,  7.25  , 13.    , 25.4667,  7.775 , 13.5   ,
       31.3875, 10.5   ,  7.55  , 26.    , 26.25  , 10.5   , 12.275 ,
       14.4542, 15.5   , 10.5   ,  7.125 ,  7.225 ,  7.775 , 14.5   ,
       52.5542, 26.    ,  7.25  , 10.4625, 26.55  , 16.1   , 20.2125,
       15.2458, 26.    ,  7.75  , 31.3875,  0.    ,  7.75  , 10.5   ,
       39.6875,  7.775 , 31.    ,  0.    , 19.5   , 29.7   ,  7.75  ,
        7.75  ,  0.    , 29.125 , 20.25  ,  7.75  ,  7.8542,  9.5   ,
        8.05  , 26.    ,  8.6625,  9.5   ,  7.8958, 13.    ,  7.75  ,
       12.875 ,  8.85  ,  7.8958, 27.7208,  7.2292, 30.5   ,  7.75  ,
       23.25  ,  0.    , 12.35  ,  8.05  , 24.    , 56.9292, 26.    ,
        7.8958, 26.25  ,  7.8542, 26.    , 14.    ,  7.25  ,  7.8958,
       12.35  , 29.    ,  6.2375, 13.    , 20.525 , 57.9792, 23.25  ,
       28.5   , 18.    ,  7.8958,  8.05  , 35.5   , 26.    , 13.    ,
       13.    , 13.    , 13.    , 13.    , 16.1   , 15.9   ,  8.6625,
        9.225 , 35.    ,  7.2292, 17.8   ,  7.225 ,  9.5   , 55.    ,
       13.    ,  7.8792,  7.8792, 27.9   , 27.7208, 14.4542,  7.05  ,
       15.5   ,  7.25  ,  7.2292,  7.75  , 55.4417,  6.4958,  8.05  ,
       21.075 ,  7.25  ,  4.0125,  7.775 , 15.7417,  7.925 , 52.    ,
        7.8958, 46.9   , 13.    ,  7.7292, 12.    ,  7.7958,  7.925 ,
       16.7   ,  7.7958,  7.8542, 26.    , 10.5   , 12.65  ,  7.925 ,
        8.05  ,  9.825 , 15.85  ,  8.6625, 21.    ,  7.75  , 18.75  ,
        7.775 , 25.4667,  7.8958,  6.8583,  0.    ,  7.925 ,  8.05  ,
       32.5   , 13.    , 13.    , 24.15  ,  7.8958,  7.7333,  7.875 ,
       14.4   , 20.2125,  7.25  , 26.    , 26.    ,  7.75  ,  8.05  ,
       26.55  , 16.1   , 26.    ,  7.125 , 55.9   , 34.375 , 18.75  ,
       10.5   , 26.25  ,  9.5   ,  7.775 , 13.    ,  8.1125, 19.5   ,
       26.55  , 19.2583, 30.5   , 27.75  , 19.9667, 27.75  ,  8.05  ,
        7.8958, 26.55  , 51.8625, 10.5   ,  7.75  , 26.55  ,  8.05  ,
       38.5   , 13.    ,  8.05  ,  7.05  ,  0.    , 26.55  ,  7.725 ,
       19.2583,  7.25  ,  8.6625, 27.75  , 13.7917,  9.8375, 52.    ,
       21.    ,  7.0458,  7.5208, 12.2875, 46.9   ,  0.    ,  8.05  ,
        9.5875, 25.4667, 29.7   ,  8.05  , 15.9   , 19.9667,  7.25  ,
       30.5   , 49.5042,  8.05  , 14.4583, 15.1   ,  7.7958,  8.6625,
        7.75  ,  7.6292,  9.5875, 26.    , 26.55  , 22.525 , 56.4958,
        7.75  ,  8.05  , 26.2875, 59.4   ,  7.4958, 34.0208, 10.5   ,
       24.15  , 26.    ,  7.8958,  7.8958,  7.225 , 57.9792,  7.2292,
        7.75  , 10.5   ,  7.925 , 11.5   , 26.    ,  7.2292,  7.2292,
       22.3583,  8.6625, 26.25  , 26.55  , 14.5   , 49.5   , 31.275 ,
       31.275 , 26.    , 26.    , 26.    , 13.8625, 20.525 , 36.75  ,
       26.    ,  7.8292,  7.225 ,  7.775 , 26.55  , 39.6   , 17.4   ,
        7.75  ,  7.8958, 13.5   ,  8.05  ,  8.05  , 24.15  ,  7.8958,
       21.075 ,  7.2292,  7.8542, 10.5   , 51.4792, 26.3875,  7.75  ,
        8.05  , 14.5   , 13.    , 55.9   , 14.4583,  7.925 , 30.    ,
       26.    , 40.125 ,  8.7125, 15.    ,  8.05  ,  8.05  ,  7.125 ,
        7.25  ,  7.75  , 26.    , 24.15  , 33.    ,  0.    ,  7.225 ,
       56.9292, 27.    ,  7.8958, 42.4   ,  8.05  , 26.55  , 15.55  ,
        7.8958, 30.5   , 41.5792, 31.275 ,  7.05  , 15.5   ,  7.75  ,
        8.05  , 65.    , 14.4   , 16.1   , 39.    , 10.5   , 14.4542,
       52.5542, 15.7417,  7.8542, 16.1   , 32.3208, 12.35  ,  7.8958,
        7.7333, 30.    ,  7.0542, 30.5   ,  0.    , 27.9   , 13.    ,
        7.925 , 26.25  , 39.6875, 16.1   ,  7.8542, 27.9   , 56.4958,
       19.2583,  7.8958, 35.5   ,  7.55  ,  7.55  ,  7.8958, 23.    ,
        8.4333,  7.8292,  6.75  ,  7.8958, 15.5   , 13.    ,  7.225 ,
       25.5875,  7.4958,  7.925 , 13.    ,  7.775 ,  8.05  , 52.    ,
       39.    , 52.    , 10.5   , 13.    ,  0.    ,  7.775 ,  8.05  ,
        9.8417, 46.9   ,  8.1375,  9.225 , 46.9   , 39.    , 41.5792,
       39.6875, 10.1708,  7.7958, 57.    , 13.4167, 56.4958,  7.225 ,
       26.55  , 13.5   ,  8.05  ,  7.7333,  7.65  , 26.2875, 14.4542,
        7.7417,  7.8542, 26.    , 13.5   , 26.2875, 15.2458, 49.5042,
       26.55  , 52.    ,  9.4833, 13.    ,  7.65  , 10.5   , 15.5   ,
        7.775 , 33.    ,  7.0542, 13.    , 13.    , 53.1   ,  8.6625,
       21.    ,  7.7375, 26.    ,  7.925 , 18.7875,  0.    , 13.    ,
       13.    , 16.1   , 34.375 ,  7.8958,  7.8958, 30.    , 16.1   ,
        7.925 , 20.25  , 13.    , 53.1   ,  7.75  , 23.    , 12.475 ,
        9.5   ,  7.8958, 65.    , 14.5   ,  7.7958, 11.5   ,  8.05  ,
       14.5   ,  7.125 ,  7.2292,  7.775 , 39.6   ,  7.75  , 24.15  ,
        8.3625,  9.5   ,  7.8542, 10.5   ,  7.225 , 23.    ,  7.75  ,
        7.75  , 12.475 ,  7.7375,  7.2292, 57.    , 30.    , 23.45  ,
        7.05  ,  7.25  ,  7.4958, 29.125 , 20.575 ,  7.75  , 26.    ,
       30.6958,  7.8958, 13.    , 25.9292,  8.6833,  7.2292, 24.15  ,
       13.    , 26.25  ,  8.5167,  6.975 ,  7.775 ,  0.    ,  7.775 ,
       13.    , 53.1   ,  7.8875, 24.15  , 10.5   , 31.275 ,  8.05  ,
        0.    ,  7.925 , 37.0042,  6.45  , 27.9   ,  8.6625,  0.    ,
       12.475 , 39.6875,  6.95  , 56.4958, 37.0042,  7.75  , 14.4542,
       18.75  ,  7.2292,  7.8542,  8.3   ,  8.6625,  8.05  , 56.4958,
       29.7   ,  7.925 , 10.5   , 31.    ,  6.4375,  8.6625,  7.55  ,
        7.8958, 33.    , 31.275 ,  7.775 , 15.2458, 39.4   , 26.    ,
        9.35  , 26.55  , 19.2583,  7.2292, 14.1083, 11.5   , 25.9292,
       13.    , 13.    , 13.8583, 50.4958,  9.5   , 11.1333,  7.8958,
       52.5542,  5.    ,  9.    , 24.    ,  7.225 ,  9.8458,  7.8958,
        7.8958, 26.    ,  7.8958, 10.5167, 10.5   ,  7.05  , 29.125 ,
       13.    , 30.    , 23.45  , 30.    ,  7.75  ])

In [29]:
np.array(df['Fare']).reshape(-1, 1)

array([[ 7.25  ],
       [ 7.925 ],
       [53.1   ],
       [ 8.05  ],
       [ 8.4583],
       [51.8625],
       [21.075 ],
       [11.1333],
       [30.0708],
       [16.7   ],
       [26.55  ],
       [ 8.05  ],
       [31.275 ],
       [ 7.8542],
       [16.    ],
       [29.125 ],
       [13.    ],
       [18.    ],
       [ 7.225 ],
       [26.    ],
       [13.    ],
       [ 8.0292],
       [35.5   ],
       [21.075 ],
       [31.3875],
       [ 7.225 ],
       [ 7.8792],
       [ 7.8958],
       [27.7208],
       [ 7.75  ],
       [10.5   ],
       [52.    ],
       [ 7.2292],
       [ 8.05  ],
       [18.    ],
       [11.2417],
       [ 9.475 ],
       [21.    ],
       [ 7.8958],
       [41.5792],
       [ 7.8792],
       [ 8.05  ],
       [15.5   ],
       [ 7.75  ],
       [21.6792],
       [17.8   ],
       [39.6875],
       [ 7.8   ],
       [26.    ],
       [61.9792],
       [35.5   ],
       [10.5   ],
       [ 7.2292],
       [27.75  ],
       [46.9   ],
       [ 7.2292],
       [27.9   ],
       [27.7208],
       [15.2458],
       [10.5   ],
       [ 8.1583],
       [ 7.925 ],
       [ 8.6625],
       [10.5   ],
       [46.9   ],
       [14.4542],
       [56.4958],
       [ 7.65  ],
       [ 7.8958],
       [ 8.05  ],
       [29.    ],
       [12.475 ],
       [ 9.    ],
       [ 9.5   ],
       [ 7.7875],
       [47.1   ],
       [10.5   ],
       [15.85  ],
       [34.375 ],
       [ 8.05  ],
       [ 8.05  ],
       [ 8.05  ],
       [ 7.8542],
       [61.175 ],
       [20.575 ],
       [ 7.25  ],
       [ 8.05  ],
       [34.6542],
       [63.3583],
       [23.    ],
       [26.    ],
       [ 7.8958],
       [ 7.8958],
       [ 8.6542],
       [ 7.925 ],
       [ 7.8958],
       [ 7.65  ],
       [ 7.775 ],
       [ 7.8958],
       [24.15  ],
       [52.    ],
       [14.4542],
       [ 8.05  ],
       [ 9.825 ],
       [14.4583],
       [ 7.925 ],
       [ 7.75  ],
       [21.    ],
       [31.275 ],
       [ 8.05  ],
       [30.0708],
       [13.    ],
       [11.2417],
       [ 7.75  ],
       [ 7.1417],
       [22.3583],
       [ 6.975 ],
       [ 7.8958],
       [ 7.05  ],
       [14.5   ],
       [26.    ],
       [13.    ],
       [15.0458],
       [26.2833],
       [53.1   ],
       [ 9.2167],
       [15.2458],
       [ 7.75  ],
       [15.85  ],
       [ 6.75  ],
       [11.5   ],
       [36.75  ],
       [ 7.7958],
       [34.375 ],
       [26.    ],
       [13.    ],
       [12.525 ],
       [ 8.05  ],
       [14.5   ],
       [ 7.3125],
       [61.3792],
       [ 7.7333],
       [ 8.05  ],
       [ 8.6625],
       [16.1   ],
       [15.75  ],
       [ 7.775 ],
       [ 8.6625],
       [39.6875],
       [20.525 ],
       [55.    ],
       [27.9   ],
       [25.925 ],
       [56.4958],
       [33.5   ],
       [29.125 ],
       [11.1333],
       [ 7.925 ],
       [30.6958],
       [ 7.8542],
       [25.4667],
       [28.7125],
       [13.    ],
       [ 0.    ],
       [15.05  ],
       [31.3875],
       [39.    ],
       [22.025 ],
       [50.    ],
       [15.5   ],
       [26.55  ],
       [15.5   ],
       [ 7.8958],
       [13.    ],
       [13.    ],
       [ 7.8542],
       [26.    ],
       [27.7208],
       [ 7.75  ],
       [ 8.4042],
       [ 7.75  ],
       [13.    ],
       [ 9.5   ],
       [ 6.4958],
       [ 7.225 ],
       [ 8.05  ],
       [10.4625],
       [15.85  ],
       [18.7875],
       [ 7.75  ],
       [31.    ],
       [ 7.05  ],
       [21.    ],
       [ 7.25  ],
       [13.    ],
       [ 7.75  ],
       [ 7.925 ],
       [27.    ],
       [10.5   ],
       [ 8.05  ],
       [13.    ],
       [ 8.05  ],
       [ 7.8958],
       [ 9.35  ],
       [10.5   ],
       [ 7.25  ],
       [13.    ],
       [25.4667],
       [ 7.775 ],
       [13.5   ],
       [31.3875],
       [10.5   ],
       [ 7.55  ],
       [26.    ],
       [26.25  ],
       [10.5   ],
       [12.275 ],
       [14.4542],
       [15.5   ],
       [10.5   ],
       [ 7.125 ],
       [ 7.225 ],
       [ 7.775 ],
       [14.5   ],
       [52.5542],
       [26.    ],
       [ 7.25  ],
       [10.4625],
       [26.55  ],
       [16.1   ],
       [20.2125],
       [15.2458],
       [26.    ],
       [ 7.75  ],
       [31.3875],
       [ 0.    ],
       [ 7.75  ],
       [10.5   ],
       [39.6875],
       [ 7.775 ],
       [31.    ],
       [ 0.    ],
       [19.5   ],
       [29.7   ],
       [ 7.75  ],
       [ 7.75  ],
       [ 0.    ],
       [29.125 ],
       [20.25  ],
       [ 7.75  ],
       [ 7.8542],
       [ 9.5   ],
       [ 8.05  ],
       [26.    ],
       [ 8.6625],
       [ 9.5   ],
       [ 7.8958],
       [13.    ],
       [ 7.75  ],
       [12.875 ],
       [ 8.85  ],
       [ 7.8958],
       [27.7208],
       [ 7.2292],
       [30.5   ],
       [ 7.75  ],
       [23.25  ],
       [ 0.    ],
       [12.35  ],
       [ 8.05  ],
       [24.    ],
       [56.9292],
       [26.    ],
       [ 7.8958],
       [26.25  ],
       [ 7.8542],
       [26.    ],
       [14.    ],
       [ 7.25  ],
       [ 7.8958],
       [12.35  ],
       [29.    ],
       [ 6.2375],
       [13.    ],
       [20.525 ],
       [57.9792],
       [23.25  ],
       [28.5   ],
       [18.    ],
       [ 7.8958],
       [ 8.05  ],
       [35.5   ],
       [26.    ],
       [13.    ],
       [13.    ],
       [13.    ],
       [13.    ],
       [13.    ],
       [16.1   ],
       [15.9   ],
       [ 8.6625],
       [ 9.225 ],
       [35.    ],
       [ 7.2292],
       [17.8   ],
       [ 7.225 ],
       [ 9.5   ],
       [55.    ],
       [13.    ],
       [ 7.8792],
       [ 7.8792],
       [27.9   ],
       [27.7208],
       [14.4542],
       [ 7.05  ],
       [15.5   ],
       [ 7.25  ],
       [ 7.2292],
       [ 7.75  ],
       [55.4417],
       [ 6.4958],
       [ 8.05  ],
       [21.075 ],
       [ 7.25  ],
       [ 4.0125],
       [ 7.775 ],
       [15.7417],
       [ 7.925 ],
       [52.    ],
       [ 7.8958],
       [46.9   ],
       [13.    ],
       [ 7.7292],
       [12.    ],
       [ 7.7958],
       [ 7.925 ],
       [16.7   ],
       [ 7.7958],
       [ 7.8542],
       [26.    ],
       [10.5   ],
       [12.65  ],
       [ 7.925 ],
       [ 8.05  ],
       [ 9.825 ],
       [15.85  ],
       [ 8.6625],
       [21.    ],
       [ 7.75  ],
       [18.75  ],
       [ 7.775 ],
       [25.4667],
       [ 7.8958],
       [ 6.8583],
       [ 0.    ],
       [ 7.925 ],
       [ 8.05  ],
       [32.5   ],
       [13.    ],
       [13.    ],
       [24.15  ],
       [ 7.8958],
       [ 7.7333],
       [ 7.875 ],
       [14.4   ],
       [20.2125],
       [ 7.25  ],
       [26.    ],
       [26.    ],
       [ 7.75  ],
       [ 8.05  ],
       [26.55  ],
       [16.1   ],
       [26.    ],
       [ 7.125 ],
       [55.9   ],
       [34.375 ],
       [18.75  ],
       [10.5   ],
       [26.25  ],
       [ 9.5   ],
       [ 7.775 ],
       [13.    ],
       [ 8.1125],
       [19.5   ],
       [26.55  ],
       [19.2583],
       [30.5   ],
       [27.75  ],
       [19.9667],
       [27.75  ],
       [ 8.05  ],
       [ 7.8958],
       [26.55  ],
       [51.8625],
       [10.5   ],
       [ 7.75  ],
       [26.55  ],
       [ 8.05  ],
       [38.5   ],
       [13.    ],
       [ 8.05  ],
       [ 7.05  ],
       [ 0.    ],
       [26.55  ],
       [ 7.725 ],
       [19.2583],
       [ 7.25  ],
       [ 8.6625],
       [27.75  ],
       [13.7917],
       [ 9.8375],
       [52.    ],
       [21.    ],
       [ 7.0458],
       [ 7.5208],
       [12.2875],
       [46.9   ],
       [ 0.    ],
       [ 8.05  ],
       [ 9.5875],
       [25.4667],
       [29.7   ],
       [ 8.05  ],
       [15.9   ],
       [19.9667],
       [ 7.25  ],
       [30.5   ],
       [49.5042],
       [ 8.05  ],
       [14.4583],
       [15.1   ],
       [ 7.7958],
       [ 8.6625],
       [ 7.75  ],
       [ 7.6292],
       [ 9.5875],
       [26.    ],
       [26.55  ],
       [22.525 ],
       [56.4958],
       [ 7.75  ],
       [ 8.05  ],
       [26.2875],
       [59.4   ],
       [ 7.4958],
       [34.0208],
       [10.5   ],
       [24.15  ],
       [26.    ],
       [ 7.8958],
       [ 7.8958],
       [ 7.225 ],
       [57.9792],
       [ 7.2292],
       [ 7.75  ],
       [10.5   ],
       [ 7.925 ],
       [11.5   ],
       [26.    ],
       [ 7.2292],
       [ 7.2292],
       [22.3583],
       [ 8.6625],
       [26.25  ],
       [26.55  ],
       [14.5   ],
       [49.5   ],
       [31.275 ],
       [31.275 ],
       [26.    ],
       [26.    ],
       [26.    ],
       [13.8625],
       [20.525 ],
       [36.75  ],
       [26.    ],
       [ 7.8292],
       [ 7.225 ],
       [ 7.775 ],
       [26.55  ],
       [39.6   ],
       [17.4   ],
       [ 7.75  ],
       [ 7.8958],
       [13.5   ],
       [ 8.05  ],
       [ 8.05  ],
       [24.15  ],
       [ 7.8958],
       [21.075 ],
       [ 7.2292],
       [ 7.8542],
       [10.5   ],
       [51.4792],
       [26.3875],
       [ 7.75  ],
       [ 8.05  ],
       [14.5   ],
       [13.    ],
       [55.9   ],
       [14.4583],
       [ 7.925 ],
       [30.    ],
       [26.    ],
       [40.125 ],
       [ 8.7125],
       [15.    ],
       [ 8.05  ],
       [ 8.05  ],
       [ 7.125 ],
       [ 7.25  ],
       [ 7.75  ],
       [26.    ],
       [24.15  ],
       [33.    ],
       [ 0.    ],
       [ 7.225 ],
       [56.9292],
       [27.    ],
       [ 7.8958],
       [42.4   ],
       [ 8.05  ],
       [26.55  ],
       [15.55  ],
       [ 7.8958],
       [30.5   ],
       [41.5792],
       [31.275 ],
       [ 7.05  ],
       [15.5   ],
       [ 7.75  ],
       [ 8.05  ],
       [65.    ],
       [14.4   ],
       [16.1   ],
       [39.    ],
       [10.5   ],
       [14.4542],
       [52.5542],
       [15.7417],
       [ 7.8542],
       [16.1   ],
       [32.3208],
       [12.35  ],
       [ 7.8958],
       [ 7.7333],
       [30.    ],
       [ 7.0542],
       [30.5   ],
       [ 0.    ],
       [27.9   ],
       [13.    ],
       [ 7.925 ],
       [26.25  ],
       [39.6875],
       [16.1   ],
       [ 7.8542],
       [27.9   ],
       [56.4958],
       [19.2583],
       [ 7.8958],
       [35.5   ],
       [ 7.55  ],
       [ 7.55  ],
       [ 7.8958],
       [23.    ],
       [ 8.4333],
       [ 7.8292],
       [ 6.75  ],
       [ 7.8958],
       [15.5   ],
       [13.    ],
       [ 7.225 ],
       [25.5875],
       [ 7.4958],
       [ 7.925 ],
       [13.    ],
       [ 7.775 ],
       [ 8.05  ],
       [52.    ],
       [39.    ],
       [52.    ],
       [10.5   ],
       [13.    ],
       [ 0.    ],
       [ 7.775 ],
       [ 8.05  ],
       [ 9.8417],
       [46.9   ],
       [ 8.1375],
       [ 9.225 ],
       [46.9   ],
       [39.    ],
       [41.5792],
       [39.6875],
       [10.1708],
       [ 7.7958],
       [57.    ],
       [13.4167],
       [56.4958],
       [ 7.225 ],
       [26.55  ],
       [13.5   ],
       [ 8.05  ],
       [ 7.7333],
       [ 7.65  ],
       [26.2875],
       [14.4542],
       [ 7.7417],
       [ 7.8542],
       [26.    ],
       [13.5   ],
       [26.2875],
       [15.2458],
       [49.5042],
       [26.55  ],
       [52.    ],
       [ 9.4833],
       [13.    ],
       [ 7.65  ],
       [10.5   ],
       [15.5   ],
       [ 7.775 ],
       [33.    ],
       [ 7.0542],
       [13.    ],
       [13.    ],
       [53.1   ],
       [ 8.6625],
       [21.    ],
       [ 7.7375],
       [26.    ],
       [ 7.925 ],
       [18.7875],
       [ 0.    ],
       [13.    ],
       [13.    ],
       [16.1   ],
       [34.375 ],
       [ 7.8958],
       [ 7.8958],
       [30.    ],
       [16.1   ],
       [ 7.925 ],
       [20.25  ],
       [13.    ],
       [53.1   ],
       [ 7.75  ],
       [23.    ],
       [12.475 ],
       [ 9.5   ],
       [ 7.8958],
       [65.    ],
       [14.5   ],
       [ 7.7958],
       [11.5   ],
       [ 8.05  ],
       [14.5   ],
       [ 7.125 ],
       [ 7.2292],
       [ 7.775 ],
       [39.6   ],
       [ 7.75  ],
       [24.15  ],
       [ 8.3625],
       [ 9.5   ],
       [ 7.8542],
       [10.5   ],
       [ 7.225 ],
       [23.    ],
       [ 7.75  ],
       [ 7.75  ],
       [12.475 ],
       [ 7.7375],
       [ 7.2292],
       [57.    ],
       [30.    ],
       [23.45  ],
       [ 7.05  ],
       [ 7.25  ],
       [ 7.4958],
       [29.125 ],
       [20.575 ],
       [ 7.75  ],
       [26.    ],
       [30.6958],
       [ 7.8958],
       [13.    ],
       [25.9292],
       [ 8.6833],
       [ 7.2292],
       [24.15  ],
       [13.    ],
       [26.25  ],
       [ 8.5167],
       [ 6.975 ],
       [ 7.775 ],
       [ 0.    ],
       [ 7.775 ],
       [13.    ],
       [53.1   ],
       [ 7.8875],
       [24.15  ],
       [10.5   ],
       [31.275 ],
       [ 8.05  ],
       [ 0.    ],
       [ 7.925 ],
       [37.0042],
       [ 6.45  ],
       [27.9   ],
       [ 8.6625],
       [ 0.    ],
       [12.475 ],
       [39.6875],
       [ 6.95  ],
       [56.4958],
       [37.0042],
       [ 7.75  ],
       [14.4542],
       [18.75  ],
       [ 7.2292],
       [ 7.8542],
       [ 8.3   ],
       [ 8.6625],
       [ 8.05  ],
       [56.4958],
       [29.7   ],
       [ 7.925 ],
       [10.5   ],
       [31.    ],
       [ 6.4375],
       [ 8.6625],
       [ 7.55  ],
       [ 7.8958],
       [33.    ],
       [31.275 ],
       [ 7.775 ],
       [15.2458],
       [39.4   ],
       [26.    ],
       [ 9.35  ],
       [26.55  ],
       [19.2583],
       [ 7.2292],
       [14.1083],
       [11.5   ],
       [25.9292],
       [13.    ],
       [13.    ],
       [13.8583],
       [50.4958],
       [ 9.5   ],
       [11.1333],
       [ 7.8958],
       [52.5542],
       [ 5.    ],
       [ 9.    ],
       [24.    ],
       [ 7.225 ],
       [ 9.8458],
       [ 7.8958],
       [ 7.8958],
       [26.    ],
       [ 7.8958],
       [10.5167],
       [10.5   ],
       [ 7.05  ],
       [29.125 ],
       [13.    ],
       [30.    ],
       [23.45  ],
       [30.    ],
       [ 7.75  ]])

In [30]:
scaler.fit_transform(np.array(df['Fare']).reshape(-1, 1))

array([[-7.79117066e-01],
       [-7.29372504e-01],
       [ 2.59982835e+00],
       [-7.20160548e-01],
       [-6.90070616e-01],
       [ 2.50862999e+00],
       [ 2.39725255e-01],
       [-4.92934760e-01],
       [ 9.02676557e-01],
       [-8.26932009e-02],
       [ 6.43208923e-01],
       [-7.20160548e-01],
       [ 9.91420855e-01],
       [-7.34590156e-01],
       [-1.34280154e-01],
       [ 8.32975214e-01],
       [-3.55367095e-01],
       [ 1.31111403e-02],
       [-7.80959457e-01],
       [ 6.02676317e-01],
       [-3.55367095e-01],
       [-7.21693418e-01],
       [ 1.30278496e+00],
       [ 2.39725255e-01],
       [ 9.99711616e-01],
       [-7.80959457e-01],
       [-7.32747765e-01],
       [-7.31524417e-01],
       [ 7.29491786e-01],
       [-7.42269242e-01],
       [-5.39606213e-01],
       [ 2.51876314e+00],
       [-7.80649935e-01],
       [-7.20160548e-01],
       [ 1.31111403e-02],
       [-4.84946151e-01],
       [-6.15144251e-01],
       [ 2.34198082e-01],
       [-7.31524417e-01],
       [ 1.75079554e+00],
       [-7.32747765e-01],
       [-7.20160548e-01],
       [-1.71127977e-01],
       [-7.42269242e-01],
       [ 2.84252165e-01],
       [-1.62798914e-03],
       [ 1.61138549e+00],
       [-7.38584460e-01],
       [ 6.02676317e-01],
       [ 3.25418674e+00],
       [ 1.30278496e+00],
       [-5.39606213e-01],
       [-7.80649935e-01],
       [ 7.31643699e-01],
       [ 2.14291534e+00],
       [-7.80649935e-01],
       [ 7.42698046e-01],
       [ 7.29491786e-01],
       [-1.89861411e-01],
       [-5.39606213e-01],
       [-7.12179310e-01],
       [-7.29372504e-01],
       [-6.75021964e-01],
       [-5.39606213e-01],
       [ 2.14291534e+00],
       [-2.48198885e-01],
       [ 2.85008403e+00],
       [-7.49638807e-01],
       [-7.31524417e-01],
       [-7.20160548e-01],
       [ 8.23763258e-01],
       [-3.94057310e-01],
       [-6.50149683e-01],
       [-6.13301860e-01],
       [-7.39505656e-01],
       [ 2.15765447e+00],
       [-5.39606213e-01],
       [-1.45334501e-01],
       [ 1.21987736e+00],
       [-7.20160548e-01],
       [-7.20160548e-01],
       [-7.20160548e-01],
       [-7.34590156e-01],
       [ 3.19492070e+00],
       [ 2.02877432e-01],
       [-7.79117066e-01],
       [-7.20160548e-01],
       [ 1.24045319e+00],
       [ 3.35582041e+00],
       [ 3.81589376e-01],
       [ 6.02676317e-01],
       [-7.31524417e-01],
       [-7.31524417e-01],
       [-6.75633638e-01],
       [-7.29372504e-01],
       [-7.31524417e-01],
       [-7.49638807e-01],
       [-7.40426851e-01],
       [-7.31524417e-01],
       [ 4.66339370e-01],
       [ 2.51876314e+00],
       [-2.48198885e-01],
       [-7.20160548e-01],
       [-5.89350775e-01],
       [-2.47896733e-01],
       [-7.29372504e-01],
       [-7.42269242e-01],
       [ 2.34198082e-01],
       [ 9.91420855e-01],
       [-7.20160548e-01],
       [ 9.02676557e-01],
       [-3.55367095e-01],
       [-4.84946151e-01],
       [-7.42269242e-01],
       [-7.87098304e-01],
       [ 3.34298879e-01],
       [-7.99383369e-01],
       [-7.31524417e-01],
       [-7.93856195e-01],
       [-2.44823625e-01],
       [ 6.02676317e-01],
       [-3.55367095e-01],
       [-2.04600540e-01],
       [ 6.23554294e-01],
       [ 2.59982835e+00],
       [-6.34179837e-01],
       [-1.89861411e-01],
       [-7.42269242e-01],
       [-1.45334501e-01],
       [-8.15964889e-01],
       [-4.65910566e-01],
       [ 1.39490452e+00],
       [-7.38893982e-01],
       [ 1.21987736e+00],
       [ 6.02676317e-01],
       [-3.55367095e-01],
       [-3.90372528e-01],
       [-7.20160548e-01],
       [-2.44823625e-01],
       [-7.74511088e-01],
       [ 3.20996935e+00],
       [-7.43499960e-01],
       [-7.20160548e-01],
       [-6.75021964e-01],
       [-1.26910589e-01],
       [-1.52704066e-01],
       [-7.40426851e-01],
       [-6.75021964e-01],
       [ 1.61138549e+00],
       [ 1.99192649e-01],
       [ 2.73985008e+00],
       [ 7.42698046e-01],
       [ 5.97149143e-01],
       [ 2.85008403e+00],
       [ 1.15539367e+00],
       [ 8.32975214e-01],
       [-4.92934760e-01],
       [-7.29372504e-01],
       [ 9.48736337e-01],
       [-7.34590156e-01],
       [ 5.63374428e-01],
       [ 8.02575760e-01],
       [-3.55367095e-01],
       [-1.31341051e+00],
       [-2.04291019e-01],
       [ 9.99711616e-01],
       [ 1.56071973e+00],
       [ 3.09736120e-01],
       [ 2.37137185e+00],
       [-1.71127977e-01],
       [ 6.43208923e-01],
       [-1.71127977e-01],
       [-7.31524417e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-7.34590156e-01],
       [ 6.02676317e-01],
       [ 7.29491786e-01],
       [-7.42269242e-01],
       [-6.94057550e-01],
       [-7.42269242e-01],
       [-3.55367095e-01],
       [-6.13301860e-01],
       [-8.34698323e-01],
       [-7.80959457e-01],
       [-7.20160548e-01],
       [-5.42369800e-01],
       [-1.45334501e-01],
       [ 7.11464624e-02],
       [-7.42269242e-01],
       [ 9.71154552e-01],
       [-7.93856195e-01],
       [ 2.34198082e-01],
       [-7.79117066e-01],
       [-3.55367095e-01],
       [-7.42269242e-01],
       [-7.29372504e-01],
       [ 6.76371964e-01],
       [-5.39606213e-01],
       [-7.20160548e-01],
       [-3.55367095e-01],
       [-7.20160548e-01],
       [-7.31524417e-01],
       [-6.24356207e-01],
       [-5.39606213e-01],
       [-7.79117066e-01],
       [-3.55367095e-01],
       [ 5.63374428e-01],
       [-7.40426851e-01],
       [-3.18519272e-01],
       [ 9.99711616e-01],
       [-5.39606213e-01],
       [-7.57008372e-01],
       [ 6.02676317e-01],
       [ 6.21100229e-01],
       [-5.39606213e-01],
       [-4.08796439e-01],
       [-2.48198885e-01],
       [-1.71127977e-01],
       [-5.39606213e-01],
       [-7.88329022e-01],
       [-7.80959457e-01],
       [-7.40426851e-01],
       [-2.44823625e-01],
       [ 2.55960527e+00],
       [ 6.02676317e-01],
       [-7.79117066e-01],
       [-5.42369800e-01],
       [ 6.43208923e-01],
       [-1.26910589e-01],
       [ 1.76162759e-01],
       [-1.89861411e-01],
       [ 6.02676317e-01],
       [-7.42269242e-01],
       [ 9.99711616e-01],
       [-1.31341051e+00],
       [-7.42269242e-01],
       [-5.39606213e-01],
       [ 1.61138549e+00],
       [-7.40426851e-01],
       [ 9.71154552e-01],
       [-1.31341051e+00],
       [ 1.23654611e-01],
       [ 8.75350211e-01],
       [-7.42269242e-01],
       [-7.42269242e-01],
       [-1.31341051e+00],
       [ 8.32975214e-01],
       [ 1.78926346e-01],
       [-7.42269242e-01],
       [-7.34590156e-01],
       [-6.13301860e-01],
       [-7.20160548e-01],
       [ 6.02676317e-01],
       [-6.75021964e-01],
       [-6.13301860e-01],
       [-7.31524417e-01],
       [-3.55367095e-01],
       [-7.42269242e-01],
       [-3.64579051e-01],
       [-6.61204031e-01],
       [-7.31524417e-01],
       [ 7.29491786e-01],
       [-7.80649935e-01],
       [ 9.34306729e-01],
       [-7.42269242e-01],
       [ 4.00013287e-01],
       [-1.31341051e+00],
       [-4.03269266e-01],
       [-7.20160548e-01],
       [ 4.55285023e-01],
       [ 2.88202372e+00],
       [ 6.02676317e-01],
       [-7.31524417e-01],
       [ 6.21100229e-01],
       [-7.34590156e-01],
       [ 6.02676317e-01],
       [-2.81671448e-01],
       [-7.79117066e-01],
       [-7.31524417e-01],
       [-4.03269266e-01],
       [ 8.23763258e-01],
       [-8.53733909e-01],
       [-3.55367095e-01],
       [ 1.99192649e-01],
       [ 2.95940415e+00],
       [ 4.00013287e-01],
       [ 7.86915435e-01],
       [ 1.31111403e-02],
       [-7.31524417e-01],
       [-7.20160548e-01],
       [ 1.30278496e+00],
       [ 6.02676317e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-1.26910589e-01],
       [-1.41649719e-01],
       [-6.75021964e-01],
       [-6.33568163e-01],
       [ 1.26593714e+00],
       [-7.80649935e-01],
       [-1.62798914e-03],
       [-7.80959457e-01],
       [-6.13301860e-01],
       [ 2.73985008e+00],
       [-3.55367095e-01],
       [-7.32747765e-01],
       [-7.32747765e-01],
       [ 7.42698046e-01],
       [ 7.29491786e-01],
       [-2.48198885e-01],
       [-7.93856195e-01],
       [-1.71127977e-01],
       [-7.79117066e-01],
       [-7.80649935e-01],
       [-7.42269242e-01],
       [ 2.77240145e+00],
       [-8.34698323e-01],
       [-7.20160548e-01],
       [ 2.39725255e-01],
       [-7.79117066e-01],
       [-1.01770672e+00],
       [-7.40426851e-01],
       [-1.53315740e-01],
       [-7.29372504e-01],
       [ 2.51876314e+00],
       [-7.31524417e-01],
       [ 2.14291534e+00],
       [-3.55367095e-01],
       [-7.43802112e-01],
       [-4.29062742e-01],
       [-7.38893982e-01],
       [-7.29372504e-01],
       [-8.26932009e-02],
       [-7.38893982e-01],
       [-7.34590156e-01],
       [ 6.02676317e-01],
       [-5.39606213e-01],
       [-3.81160572e-01],
       [-7.29372504e-01],
       [-7.20160548e-01],
       [-5.89350775e-01],
       [-1.45334501e-01],
       [-6.75021964e-01],
       [ 2.34198082e-01],
       [-7.42269242e-01],
       [ 6.83828756e-02],
       [-7.40426851e-01],
       [ 5.63374428e-01],
       [-7.31524417e-01],
       [-8.07983651e-01],
       [-1.31341051e+00],
       [-7.29372504e-01],
       [-7.20160548e-01],
       [ 1.08169802e+00],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [ 4.66339370e-01],
       [-7.31524417e-01],
       [-7.43499960e-01],
       [-7.33057286e-01],
       [-2.52193189e-01],
       [ 1.76162759e-01],
       [-7.79117066e-01],
       [ 6.02676317e-01],
       [ 6.02676317e-01],
       [-7.42269242e-01],
       [-7.20160548e-01],
       [ 6.43208923e-01],
       [-1.26910589e-01],
       [ 6.02676317e-01],
       [-7.88329022e-01],
       [ 2.80617616e+00],
       [ 1.21987736e+00],
       [ 6.83828756e-02],
       [-5.39606213e-01],
       [ 6.21100229e-01],
       [-6.13301860e-01],
       [-7.40426851e-01],
       [-3.55367095e-01],
       [-7.15554570e-01],
       [ 1.23654611e-01],
       [ 6.43208923e-01],
       [ 1.05842373e-01],
       [ 9.34306729e-01],
       [ 7.31643699e-01],
       [ 1.58048369e-01],
       [ 7.31643699e-01],
       [-7.20160548e-01],
       [-7.31524417e-01],
       [ 6.43208923e-01],
       [ 2.50862999e+00],
       [-5.39606213e-01],
       [-7.42269242e-01],
       [ 6.43208923e-01],
       [-7.20160548e-01],
       [ 1.52387191e+00],
       [-3.55367095e-01],
       [-7.20160548e-01],
       [-7.93856195e-01],
       [-1.31341051e+00],
       [ 6.43208923e-01],
       [-7.44111634e-01],
       [ 1.05842373e-01],
       [-7.79117066e-01],
       [-6.75021964e-01],
       [ 7.31643699e-01],
       [-2.97022251e-01],
       [-5.88429579e-01],
       [ 2.51876314e+00],
       [ 2.34198082e-01],
       [-7.94165717e-01],
       [-7.59160285e-01],
       [-4.07875244e-01],
       [ 2.14291534e+00],
       [-1.31341051e+00],
       [-7.20160548e-01],
       [-6.06853491e-01],
       [ 5.63374428e-01],
       [ 8.75350211e-01],
       [-7.20160548e-01],
       [-1.41649719e-01],
       [ 1.58048369e-01],
       [-7.79117066e-01],
       [ 9.34306729e-01],
       [ 2.33483355e+00],
       [-7.20160548e-01],
       [-2.47896733e-01],
       [-2.00606236e-01],
       [-7.38893982e-01],
       [-6.75021964e-01],
       [-7.42269242e-01],
       [-7.51171677e-01],
       [-6.06853491e-01],
       [ 6.02676317e-01],
       [ 6.43208923e-01],
       [ 3.46583943e-01],
       [ 2.85008403e+00],
       [-7.42269242e-01],
       [-7.20160548e-01],
       [ 6.23863815e-01],
       [ 3.06411093e+00],
       [-7.61002676e-01],
       [ 1.19377436e+00],
       [-5.39606213e-01],
       [ 4.66339370e-01],
       [ 6.02676317e-01],
       [-7.31524417e-01],
       [-7.31524417e-01],
       [-7.80959457e-01],
       [ 2.95940415e+00],
       [-7.80649935e-01],
       [-7.42269242e-01],
       [-5.39606213e-01],
       [-7.29372504e-01],
       [-4.65910566e-01],
       [ 6.02676317e-01],
       [-7.80649935e-01],
       [-7.80649935e-01],
       [ 3.34298879e-01],
       [-6.75021964e-01],
       [ 6.21100229e-01],
       [ 6.43208923e-01],
       [-2.44823625e-01],
       [ 2.33452402e+00],
       [ 9.91420855e-01],
       [ 9.91420855e-01],
       [ 6.02676317e-01],
       [ 6.02676317e-01],
       [ 6.02676317e-01],
       [-2.91804600e-01],
       [ 1.99192649e-01],
       [ 1.39490452e+00],
       [ 6.02676317e-01],
       [-7.36432547e-01],
       [-7.80959457e-01],
       [-7.40426851e-01],
       [ 6.43208923e-01],
       [ 1.60493712e+00],
       [-3.11062480e-02],
       [-7.42269242e-01],
       [-7.31524417e-01],
       [-3.18519272e-01],
       [-7.20160548e-01],
       [-7.20160548e-01],
       [ 4.66339370e-01],
       [-7.31524417e-01],
       [ 2.39725255e-01],
       [-7.80649935e-01],
       [-7.34590156e-01],
       [-5.39606213e-01],
       [ 2.48038245e+00],
       [ 6.31233380e-01],
       [-7.42269242e-01],
       [-7.20160548e-01],
       [-2.44823625e-01],
       [-3.55367095e-01],
       [ 2.80617616e+00],
       [-2.47896733e-01],
       [-7.29372504e-01],
       [ 8.97458905e-01],
       [ 6.02676317e-01],
       [ 1.64362733e+00],
       [-6.71337182e-01],
       [-2.07975801e-01],
       [-7.20160548e-01],
       [-7.20160548e-01],
       [-7.88329022e-01],
       [-7.79117066e-01],
       [-7.42269242e-01],
       [ 6.02676317e-01],
       [ 4.66339370e-01],
       [ 1.11854585e+00],
       [-1.31341051e+00],
       [-7.80959457e-01],
       [ 2.88202372e+00],
       [ 6.76371964e-01],
       [-7.31524417e-01],
       [ 1.81128493e+00],
       [-7.20160548e-01],
       [ 6.43208923e-01],
       [-1.67443195e-01],
       [-7.31524417e-01],
       [ 9.34306729e-01],
       [ 1.75079554e+00],
       [ 9.91420855e-01],
       [-7.93856195e-01],
       [-1.71127977e-01],
       [-7.42269242e-01],
       [-7.20160548e-01],
       [ 3.47680655e+00],
       [-2.52193189e-01],
       [-1.26910589e-01],
       [ 1.56071973e+00],
       [-5.39606213e-01],
       [-2.48198885e-01],
       [ 2.55960527e+00],
       [-1.53315740e-01],
       [-7.34590156e-01],
       [-1.26910589e-01],
       [ 1.06849176e+00],
       [-4.03269266e-01],
       [-7.31524417e-01],
       [-7.43499960e-01],
       [ 8.97458905e-01],
       [-7.93546674e-01],
       [ 9.34306729e-01],
       [-1.31341051e+00],
       [ 7.42698046e-01],
       [-3.55367095e-01],
       [-7.29372504e-01],
       [ 6.21100229e-01],
       [ 1.61138549e+00],
       [-1.26910589e-01],
       [-7.34590156e-01],
       [ 7.42698046e-01],
       [ 2.85008403e+00],
       [ 1.05842373e-01],
       [-7.31524417e-01],
       [ 1.30278496e+00],
       [-7.57008372e-01],
       [-7.57008372e-01],
       [-7.31524417e-01],
       [ 3.81589376e-01],
       [-6.91913007e-01],
       [-7.36432547e-01],
       [-8.15964889e-01],
       [-7.31524417e-01],
       [-1.71127977e-01],
       [-3.55367095e-01],
       [-7.80959457e-01],
       [ 5.72276863e-01],
       [-7.61002676e-01],
       [-7.29372504e-01],
       [-3.55367095e-01],
       [-7.40426851e-01],
       [-7.20160548e-01],
       [ 2.51876314e+00],
       [ 1.56071973e+00],
       [ 2.51876314e+00],
       [-5.39606213e-01],
       [-3.55367095e-01],
       [-1.31341051e+00],
       [-7.40426851e-01],
       [-7.20160548e-01],
       [-5.88120057e-01],
       [ 2.14291534e+00],
       [-7.13712179e-01],
       [-6.33568163e-01],
       [ 2.14291534e+00],
       [ 1.56071973e+00],
       [ 1.75079554e+00],
       [ 1.61138549e+00],
       [-5.63866820e-01],
       [-7.38893982e-01],
       [ 2.88724138e+00],
       [-3.24658119e-01],
       [ 2.85008403e+00],
       [-7.80959457e-01],
       [ 6.43208923e-01],
       [-3.18519272e-01],
       [-7.20160548e-01],
       [-7.43499960e-01],
       [-7.49638807e-01],
       [ 6.23863815e-01],
       [-2.48198885e-01],
       [-7.42880916e-01],
       [-7.34590156e-01],
       [ 6.02676317e-01],
       [-3.18519272e-01],
       [ 6.23863815e-01],
       [-1.89861411e-01],
       [ 2.33483355e+00],
       [ 6.43208923e-01],
       [ 2.51876314e+00],
       [-6.14532577e-01],
       [-3.55367095e-01],
       [-7.49638807e-01],
       [-5.39606213e-01],
       [-1.71127977e-01],
       [-7.40426851e-01],
       [ 1.11854585e+00],
       [-7.93546674e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [ 2.59982835e+00],
       [-6.75021964e-01],
       [ 2.34198082e-01],
       [-7.43190438e-01],
       [ 6.02676317e-01],
       [-7.29372504e-01],
       [ 7.11464624e-02],
       [-1.31341051e+00],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-1.26910589e-01],
       [ 1.21987736e+00],
       [-7.31524417e-01],
       [-7.31524417e-01],
       [ 8.97458905e-01],
       [-1.26910589e-01],
       [-7.29372504e-01],
       [ 1.78926346e-01],
       [-3.55367095e-01],
       [ 2.59982835e+00],
       [-7.42269242e-01],
       [ 3.81589376e-01],
       [-3.94057310e-01],
       [-6.13301860e-01],
       [-7.31524417e-01],
       [ 3.47680655e+00],
       [-2.44823625e-01],
       [-7.38893982e-01],
       [-4.65910566e-01],
       [-7.20160548e-01],
       [-2.44823625e-01],
       [-7.88329022e-01],
       [-7.80649935e-01],
       [-7.40426851e-01],
       [ 1.60493712e+00],
       [-7.42269242e-01],
       [ 4.66339370e-01],
       [-6.97130659e-01],
       [-6.13301860e-01],
       [-7.34590156e-01],
       [-5.39606213e-01],
       [-7.80959457e-01],
       [ 3.81589376e-01],
       [-7.42269242e-01],
       [-7.42269242e-01],
       [-3.94057310e-01],
       [-7.43190438e-01],
       [-7.80649935e-01],
       [ 2.88724138e+00],
       [ 8.97458905e-01],
       [ 4.14752417e-01],
       [-7.93856195e-01],
       [-7.79117066e-01],
       [-7.61002676e-01],
       [ 8.32975214e-01],
       [ 2.02877432e-01],
       [-7.42269242e-01],
       [ 6.02676317e-01],
       [ 9.48736337e-01],
       [-7.31524417e-01],
       [-3.55367095e-01],
       [ 5.97458665e-01],
       [-6.73489095e-01],
       [-7.80649935e-01],
       [ 4.66339370e-01],
       [-3.55367095e-01],
       [ 6.21100229e-01],
       [-6.85766790e-01],
       [-7.99383369e-01],
       [-7.40426851e-01],
       [-1.31341051e+00],
       [-7.40426851e-01],
       [-3.55367095e-01],
       [ 2.59982835e+00],
       [-7.32136091e-01],
       [ 4.66339370e-01],
       [-5.39606213e-01],
       [ 9.91420855e-01],
       [-7.20160548e-01],
       [-1.31341051e+00],
       [-7.29372504e-01],
       [ 1.41363796e+00],
       [-8.38073584e-01],
       [ 7.42698046e-01],
       [-6.75021964e-01],
       [-1.31341051e+00],
       [-3.94057310e-01],
       [ 1.61138549e+00],
       [-8.01225760e-01],
       [ 2.85008403e+00],
       [ 1.41363796e+00],
       [-7.42269242e-01],
       [-2.48198885e-01],
       [ 6.83828756e-02],
       [-7.80649935e-01],
       [-7.34590156e-01],
       [-7.01736636e-01],
       [-6.75021964e-01],
       [-7.20160548e-01],
       [ 2.85008403e+00],
       [ 8.75350211e-01],
       [-7.29372504e-01],
       [-5.39606213e-01],
       [ 9.71154552e-01],
       [-8.38994779e-01],
       [-6.75021964e-01],
       [-7.57008372e-01],
       [-7.31524417e-01],
       [ 1.11854585e+00],
       [ 9.91420855e-01],
       [-7.40426851e-01],
       [-1.89861411e-01],
       [ 1.59019799e+00],
       [ 6.02676317e-01],
       [-6.24356207e-01],
       [ 6.43208923e-01],
       [ 1.05842373e-01],
       [-7.80649935e-01],
       [-2.73690209e-01],
       [-4.65910566e-01],
       [ 5.97458665e-01],
       [-3.55367095e-01],
       [-3.55367095e-01],
       [-2.92114121e-01],
       [ 2.40791015e+00],
       [-6.13301860e-01],
       [-4.92934760e-01],
       [-7.31524417e-01],
       [ 2.55960527e+00],
       [-9.44932272e-01],
       [-6.50149683e-01],
       [ 4.55285023e-01],
       [-7.80959457e-01],
       [-5.87817905e-01],
       [-7.31524417e-01],
       [-7.31524417e-01],
       [ 6.02676317e-01],
       [-7.31524417e-01],
       [-5.38375496e-01],
       [-5.39606213e-01],
       [-7.93856195e-01],

In [31]:
scaled_arr = scaler.fit_transform(np.array(df['Fare']).reshape(-1, 1))

In [32]:
scaled_arr.flatten()

array([-7.79117066e-01, -7.29372504e-01,  2.59982835e+00, -7.20160548e-01,
       -6.90070616e-01,  2.50862999e+00,  2.39725255e-01, -4.92934760e-01,
        9.02676557e-01, -8.26932009e-02,  6.43208923e-01, -7.20160548e-01,
        9.91420855e-01, -7.34590156e-01, -1.34280154e-01,  8.32975214e-01,
       -3.55367095e-01,  1.31111403e-02, -7.80959457e-01,  6.02676317e-01,
       -3.55367095e-01, -7.21693418e-01,  1.30278496e+00,  2.39725255e-01,
        9.99711616e-01, -7.80959457e-01, -7.32747765e-01, -7.31524417e-01,
        7.29491786e-01, -7.42269242e-01, -5.39606213e-01,  2.51876314e+00,
       -7.80649935e-01, -7.20160548e-01,  1.31111403e-02, -4.84946151e-01,
       -6.15144251e-01,  2.34198082e-01, -7.31524417e-01,  1.75079554e+00,
       -7.32747765e-01, -7.20160548e-01, -1.71127977e-01, -7.42269242e-01,
        2.84252165e-01, -1.62798914e-03,  1.61138549e+00, -7.38584460e-01,
        6.02676317e-01,  3.25418674e+00,  1.30278496e+00, -5.39606213e-01,
       -7.80649935e-01,  7.31643699e-01,  2.14291534e+00, -7.80649935e-01,
        7.42698046e-01,  7.29491786e-01, -1.89861411e-01, -5.39606213e-01,
       -7.12179310e-01, -7.29372504e-01, -6.75021964e-01, -5.39606213e-01,
        2.14291534e+00, -2.48198885e-01,  2.85008403e+00, -7.49638807e-01,
       -7.31524417e-01, -7.20160548e-01,  8.23763258e-01, -3.94057310e-01,
       -6.50149683e-01, -6.13301860e-01, -7.39505656e-01,  2.15765447e+00,
       -5.39606213e-01, -1.45334501e-01,  1.21987736e+00, -7.20160548e-01,
       -7.20160548e-01, -7.20160548e-01, -7.34590156e-01,  3.19492070e+00,
        2.02877432e-01, -7.79117066e-01, -7.20160548e-01,  1.24045319e+00,
        3.35582041e+00,  3.81589376e-01,  6.02676317e-01, -7.31524417e-01,
       -7.31524417e-01, -6.75633638e-01, -7.29372504e-01, -7.31524417e-01,
       -7.49638807e-01, -7.40426851e-01, -7.31524417e-01,  4.66339370e-01,
        2.51876314e+00, -2.48198885e-01, -7.20160548e-01, -5.89350775e-01,
       -2.47896733e-01, -7.29372504e-01, -7.42269242e-01,  2.34198082e-01,
        9.91420855e-01, -7.20160548e-01,  9.02676557e-01, -3.55367095e-01,
       -4.84946151e-01, -7.42269242e-01, -7.87098304e-01,  3.34298879e-01,
       -7.99383369e-01, -7.31524417e-01, -7.93856195e-01, -2.44823625e-01,
        6.02676317e-01, -3.55367095e-01, -2.04600540e-01,  6.23554294e-01,
        2.59982835e+00, -6.34179837e-01, -1.89861411e-01, -7.42269242e-01,
       -1.45334501e-01, -8.15964889e-01, -4.65910566e-01,  1.39490452e+00,
       -7.38893982e-01,  1.21987736e+00,  6.02676317e-01, -3.55367095e-01,
       -3.90372528e-01, -7.20160548e-01, -2.44823625e-01, -7.74511088e-01,
        3.20996935e+00, -7.43499960e-01, -7.20160548e-01, -6.75021964e-01,
       -1.26910589e-01, -1.52704066e-01, -7.40426851e-01, -6.75021964e-01,
        1.61138549e+00,  1.99192649e-01,  2.73985008e+00,  7.42698046e-01,
        5.97149143e-01,  2.85008403e+00,  1.15539367e+00,  8.32975214e-01,
       -4.92934760e-01, -7.29372504e-01,  9.48736337e-01, -7.34590156e-01,
        5.63374428e-01,  8.02575760e-01, -3.55367095e-01, -1.31341051e+00,
       -2.04291019e-01,  9.99711616e-01,  1.56071973e+00,  3.09736120e-01,
        2.37137185e+00, -1.71127977e-01,  6.43208923e-01, -1.71127977e-01,
       -7.31524417e-01, -3.55367095e-01, -3.55367095e-01, -7.34590156e-01,
        6.02676317e-01,  7.29491786e-01, -7.42269242e-01, -6.94057550e-01,
       -7.42269242e-01, -3.55367095e-01, -6.13301860e-01, -8.34698323e-01,
       -7.80959457e-01, -7.20160548e-01, -5.42369800e-01, -1.45334501e-01,
        7.11464624e-02, -7.42269242e-01,  9.71154552e-01, -7.93856195e-01,
        2.34198082e-01, -7.79117066e-01, -3.55367095e-01, -7.42269242e-01,
       -7.29372504e-01,  6.76371964e-01, -5.39606213e-01, -7.20160548e-01,
       -3.55367095e-01, -7.20160548e-01, -7.31524417e-01, -6.24356207e-01,
       -5.39606213e-01, -7.79117066e-01, -3.55367095e-01,  5.63374428e-01,
       -7.40426851e-01, -3.18519272e-01,  9.99711616e-01, -5.39606213e-01,
       -7.57008372e-01,  6.02676317e-01,  6.21100229e-01, -5.39606213e-01,
       -4.08796439e-01, -2.48198885e-01, -1.71127977e-01, -5.39606213e-01,
       -7.88329022e-01, -7.80959457e-01, -7.40426851e-01, -2.44823625e-01,
        2.55960527e+00,  6.02676317e-01, -7.79117066e-01, -5.42369800e-01,
        6.43208923e-01, -1.26910589e-01,  1.76162759e-01, -1.89861411e-01,
        6.02676317e-01, -7.42269242e-01,  9.99711616e-01, -1.31341051e+00,
       -7.42269242e-01, -5.39606213e-01,  1.61138549e+00, -7.40426851e-01,
        9.71154552e-01, -1.31341051e+00,  1.23654611e-01,  8.75350211e-01,
       -7.42269242e-01, -7.42269242e-01, -1.31341051e+00,  8.32975214e-01,
        1.78926346e-01, -7.42269242e-01, -7.34590156e-01, -6.13301860e-01,
       -7.20160548e-01,  6.02676317e-01, -6.75021964e-01, -6.13301860e-01,
       -7.31524417e-01, -3.55367095e-01, -7.42269242e-01, -3.64579051e-01,
       -6.61204031e-01, -7.31524417e-01,  7.29491786e-01, -7.80649935e-01,
        9.34306729e-01, -7.42269242e-01,  4.00013287e-01, -1.31341051e+00,
       -4.03269266e-01, -7.20160548e-01,  4.55285023e-01,  2.88202372e+00,
        6.02676317e-01, -7.31524417e-01,  6.21100229e-01, -7.34590156e-01,
        6.02676317e-01, -2.81671448e-01, -7.79117066e-01, -7.31524417e-01,
       -4.03269266e-01,  8.23763258e-01, -8.53733909e-01, -3.55367095e-01,
        1.99192649e-01,  2.95940415e+00,  4.00013287e-01,  7.86915435e-01,
        1.31111403e-02, -7.31524417e-01, -7.20160548e-01,  1.30278496e+00,
        6.02676317e-01, -3.55367095e-01, -3.55367095e-01, -3.55367095e-01,
       -3.55367095e-01, -3.55367095e-01, -1.26910589e-01, -1.41649719e-01,
       -6.75021964e-01, -6.33568163e-01,  1.26593714e+00, -7.80649935e-01,
       -1.62798914e-03, -7.80959457e-01, -6.13301860e-01,  2.73985008e+00,
       -3.55367095e-01, -7.32747765e-01, -7.32747765e-01,  7.42698046e-01,
        7.29491786e-01, -2.48198885e-01, -7.93856195e-01, -1.71127977e-01,
       -7.79117066e-01, -7.80649935e-01, -7.42269242e-01,  2.77240145e+00,
       -8.34698323e-01, -7.20160548e-01,  2.39725255e-01, -7.79117066e-01,
       -1.01770672e+00, -7.40426851e-01, -1.53315740e-01, -7.29372504e-01,
        2.51876314e+00, -7.31524417e-01,  2.14291534e+00, -3.55367095e-01,
       -7.43802112e-01, -4.29062742e-01, -7.38893982e-01, -7.29372504e-01,
       -8.26932009e-02, -7.38893982e-01, -7.34590156e-01,  6.02676317e-01,
       -5.39606213e-01, -3.81160572e-01, -7.29372504e-01, -7.20160548e-01,
       -5.89350775e-01, -1.45334501e-01, -6.75021964e-01,  2.34198082e-01,
       -7.42269242e-01,  6.83828756e-02, -7.40426851e-01,  5.63374428e-01,
       -7.31524417e-01, -8.07983651e-01, -1.31341051e+00, -7.29372504e-01,
       -7.20160548e-01,  1.08169802e+00, -3.55367095e-01, -3.55367095e-01,
        4.66339370e-01, -7.31524417e-01, -7.43499960e-01, -7.33057286e-01,
       -2.52193189e-01,  1.76162759e-01, -7.79117066e-01,  6.02676317e-01,
        6.02676317e-01, -7.42269242e-01, -7.20160548e-01,  6.43208923e-01,
       -1.26910589e-01,  6.02676317e-01, -7.88329022e-01,  2.80617616e+00,
        1.21987736e+00,  6.83828756e-02, -5.39606213e-01,  6.21100229e-01,
       -6.13301860e-01, -7.40426851e-01, -3.55367095e-01, -7.15554570e-01,
        1.23654611e-01,  6.43208923e-01,  1.05842373e-01,  9.34306729e-01,
        7.31643699e-01,  1.58048369e-01,  7.31643699e-01, -7.20160548e-01,
       -7.31524417e-01,  6.43208923e-01,  2.50862999e+00, -5.39606213e-01,
       -7.42269242e-01,  6.43208923e-01, -7.20160548e-01,  1.52387191e+00,
       -3.55367095e-01, -7.20160548e-01, -7.93856195e-01, -1.31341051e+00,
        6.43208923e-01, -7.44111634e-01,  1.05842373e-01, -7.79117066e-01,
       -6.75021964e-01,  7.31643699e-01, -2.97022251e-01, -5.88429579e-01,
        2.51876314e+00,  2.34198082e-01, -7.94165717e-01, -7.59160285e-01,
       -4.07875244e-01,  2.14291534e+00, -1.31341051e+00, -7.20160548e-01,
       -6.06853491e-01,  5.63374428e-01,  8.75350211e-01, -7.20160548e-01,
       -1.41649719e-01,  1.58048369e-01, -7.79117066e-01,  9.34306729e-01,
        2.33483355e+00, -7.20160548e-01, -2.47896733e-01, -2.00606236e-01,
       -7.38893982e-01, -6.75021964e-01, -7.42269242e-01, -7.51171677e-01,
       -6.06853491e-01,  6.02676317e-01,  6.43208923e-01,  3.46583943e-01,
        2.85008403e+00, -7.42269242e-01, -7.20160548e-01,  6.23863815e-01,
        3.06411093e+00, -7.61002676e-01,  1.19377436e+00, -5.39606213e-01,
        4.66339370e-01,  6.02676317e-01, -7.31524417e-01, -7.31524417e-01,
       -7.80959457e-01,  2.95940415e+00, -7.80649935e-01, -7.42269242e-01,
       -5.39606213e-01, -7.29372504e-01, -4.65910566e-01,  6.02676317e-01,
       -7.80649935e-01, -7.80649935e-01,  3.34298879e-01, -6.75021964e-01,
        6.21100229e-01,  6.43208923e-01, -2.44823625e-01,  2.33452402e+00,
        9.91420855e-01,  9.91420855e-01,  6.02676317e-01,  6.02676317e-01,
        6.02676317e-01, -2.91804600e-01,  1.99192649e-01,  1.39490452e+00,
        6.02676317e-01, -7.36432547e-01, -7.80959457e-01, -7.40426851e-01,
        6.43208923e-01,  1.60493712e+00, -3.11062480e-02, -7.42269242e-01,
       -7.31524417e-01, -3.18519272e-01, -7.20160548e-01, -7.20160548e-01,
        4.66339370e-01, -7.31524417e-01,  2.39725255e-01, -7.80649935e-01,
       -7.34590156e-01, -5.39606213e-01,  2.48038245e+00,  6.31233380e-01,
       -7.42269242e-01, -7.20160548e-01, -2.44823625e-01, -3.55367095e-01,
        2.80617616e+00, -2.47896733e-01, -7.29372504e-01,  8.97458905e-01,
        6.02676317e-01,  1.64362733e+00, -6.71337182e-01, -2.07975801e-01,
       -7.20160548e-01, -7.20160548e-01, -7.88329022e-01, -7.79117066e-01,
       -7.42269242e-01,  6.02676317e-01,  4.66339370e-01,  1.11854585e+00,
       -1.31341051e+00, -7.80959457e-01,  2.88202372e+00,  6.76371964e-01,
       -7.31524417e-01,  1.81128493e+00, -7.20160548e-01,  6.43208923e-01,
       -1.67443195e-01, -7.31524417e-01,  9.34306729e-01,  1.75079554e+00,
        9.91420855e-01, -7.93856195e-01, -1.71127977e-01, -7.42269242e-01,
       -7.20160548e-01,  3.47680655e+00, -2.52193189e-01, -1.26910589e-01,
        1.56071973e+00, -5.39606213e-01, -2.48198885e-01,  2.55960527e+00,
       -1.53315740e-01, -7.34590156e-01, -1.26910589e-01,  1.06849176e+00,
       -4.03269266e-01, -7.31524417e-01, -7.43499960e-01,  8.97458905e-01,
       -7.93546674e-01,  9.34306729e-01, -1.31341051e+00,  7.42698046e-01,
       -3.55367095e-01, -7.29372504e-01,  6.21100229e-01,  1.61138549e+00,
       -1.26910589e-01, -7.34590156e-01,  7.42698046e-01,  2.85008403e+00,
        1.05842373e-01, -7.31524417e-01,  1.30278496e+00, -7.57008372e-01,
       -7.57008372e-01, -7.31524417e-01,  3.81589376e-01, -6.91913007e-01,
       -7.36432547e-01, -8.15964889e-01, -7.31524417e-01, -1.71127977e-01,
       -3.55367095e-01, -7.80959457e-01,  5.72276863e-01, -7.61002676e-01,
       -7.29372504e-01, -3.55367095e-01, -7.40426851e-01, -7.20160548e-01,
        2.51876314e+00,  1.56071973e+00,  2.51876314e+00, -5.39606213e-01,
       -3.55367095e-01, -1.31341051e+00, -7.40426851e-01, -7.20160548e-01,
       -5.88120057e-01,  2.14291534e+00, -7.13712179e-01, -6.33568163e-01,
        2.14291534e+00,  1.56071973e+00,  1.75079554e+00,  1.61138549e+00,
       -5.63866820e-01, -7.38893982e-01,  2.88724138e+00, -3.24658119e-01,
        2.85008403e+00, -7.80959457e-01,  6.43208923e-01, -3.18519272e-01,
       -7.20160548e-01, -7.43499960e-01, -7.49638807e-01,  6.23863815e-01,
       -2.48198885e-01, -7.42880916e-01, -7.34590156e-01,  6.02676317e-01,
       -3.18519272e-01,  6.23863815e-01, -1.89861411e-01,  2.33483355e+00,
        6.43208923e-01,  2.51876314e+00, -6.14532577e-01, -3.55367095e-01,
       -7.49638807e-01, -5.39606213e-01, -1.71127977e-01, -7.40426851e-01,
        1.11854585e+00, -7.93546674e-01, -3.55367095e-01, -3.55367095e-01,
        2.59982835e+00, -6.75021964e-01,  2.34198082e-01, -7.43190438e-01,
        6.02676317e-01, -7.29372504e-01,  7.11464624e-02, -1.31341051e+00,
       -3.55367095e-01, -3.55367095e-01, -1.26910589e-01,  1.21987736e+00,
       -7.31524417e-01, -7.31524417e-01,  8.97458905e-01, -1.26910589e-01,
       -7.29372504e-01,  1.78926346e-01, -3.55367095e-01,  2.59982835e+00,
       -7.42269242e-01,  3.81589376e-01, -3.94057310e-01, -6.13301860e-01,
       -7.31524417e-01,  3.47680655e+00, -2.44823625e-01, -7.38893982e-01,
       -4.65910566e-01, -7.20160548e-01, -2.44823625e-01, -7.88329022e-01,
       -7.80649935e-01, -7.40426851e-01,  1.60493712e+00, -7.42269242e-01,
        4.66339370e-01, -6.97130659e-01, -6.13301860e-01, -7.34590156e-01,
       -5.39606213e-01, -7.80959457e-01,  3.81589376e-01, -7.42269242e-01,
       -7.42269242e-01, -3.94057310e-01, -7.43190438e-01, -7.80649935e-01,
        2.88724138e+00,  8.97458905e-01,  4.14752417e-01, -7.93856195e-01,
       -7.79117066e-01, -7.61002676e-01,  8.32975214e-01,  2.02877432e-01,
       -7.42269242e-01,  6.02676317e-01,  9.48736337e-01, -7.31524417e-01,
       -3.55367095e-01,  5.97458665e-01, -6.73489095e-01, -7.80649935e-01,
        4.66339370e-01, -3.55367095e-01,  6.21100229e-01, -6.85766790e-01,
       -7.99383369e-01, -7.40426851e-01, -1.31341051e+00, -7.40426851e-01,
       -3.55367095e-01,  2.59982835e+00, -7.32136091e-01,  4.66339370e-01,
       -5.39606213e-01,  9.91420855e-01, -7.20160548e-01, -1.31341051e+00,
       -7.29372504e-01,  1.41363796e+00, -8.38073584e-01,  7.42698046e-01,
       -6.75021964e-01, -1.31341051e+00, -3.94057310e-01,  1.61138549e+00,
       -8.01225760e-01,  2.85008403e+00,  1.41363796e+00, -7.42269242e-01,
       -2.48198885e-01,  6.83828756e-02, -7.80649935e-01, -7.34590156e-01,
       -7.01736636e-01, -6.75021964e-01, -7.20160548e-01,  2.85008403e+00,
        8.75350211e-01, -7.29372504e-01, -5.39606213e-01,  9.71154552e-01,
       -8.38994779e-01, -6.75021964e-01, -7.57008372e-01, -7.31524417e-01,
        1.11854585e+00,  9.91420855e-01, -7.40426851e-01, -1.89861411e-01,
        1.59019799e+00,  6.02676317e-01, -6.24356207e-01,  6.43208923e-01,
        1.05842373e-01, -7.80649935e-01, -2.73690209e-01, -4.65910566e-01,
        5.97458665e-01, -3.55367095e-01, -3.55367095e-01, -2.92114121e-01,
        2.40791015e+00, -6.13301860e-01, -4.92934760e-01, -7.31524417e-01,
        2.55960527e+00, -9.44932272e-01, -6.50149683e-01,  4.55285023e-01,
       -7.80959457e-01, -5.87817905e-01, -7.31524417e-01, -7.31524417e-01,
        6.02676317e-01, -7.31524417e-01, -5.38375496e-01, -5.39606213e-01,
       -7.93856195e-01,  8.32975214e-01, -3.55367095e-01,  8.97458905e-01,
        4.14752417e-01,  8.97458905e-01, -7.42269242e-01])

In [33]:
pd.Series(scaled_arr.flatten())

0     -0.779117
1     -0.729373
2      2.599828
3     -0.720161
4     -0.690071
         ...
770   -0.355367
771    0.897459
772    0.414752
773    0.897459
774   -0.742269
Length: 775, dtype: float64

In [34]:
df['Fare'] = pd.Series(scaled_arr.flatten())

In [35]:
df

     Survived  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0           0       3    0  22.0      1      0 -0.779117         1
1           1       3    1  26.0      0      0 -0.729373         1
2           1       1    1  35.0      1      0  2.599828         1
3           0       3    0  35.0      0      0 -0.720161         1
4           0       3    0  24.0      0      0 -0.690071         0
..        ...     ...  ...   ...    ...    ...       ...       ...
770         0       2    0  27.0      0      0 -0.355367         1
771         1       1    1  19.0      0      0  0.897459         1
772         0       3    1  24.0      1      2  0.414752         1
773         1       1    0  26.0      0      0  0.897459         2
774         0       3    0  32.0      0      0 -0.742269         0

[775 rows x 8 columns]

In [36]:
scaled_age = scaler.fit_transform(df[['Age']])

df['Age'] = scaled_age.flatten()

In [37]:
df

     Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0           0       3    0 -0.457434      1      0 -0.779117         1
1           1       3    1 -0.147969      0      0 -0.729373         1
2           1       1    1  0.548327      1      0  2.599828         1
3           0       3    0  0.548327      0      0 -0.720161         1
4           0       3    0 -0.302702      0      0 -0.690071         0
..        ...     ...  ...       ...    ...    ...       ...       ...
770         0       2    0 -0.070603      0      0 -0.355367         1
771         1       1    1 -0.689533      0      0  0.897459         1
772         0       3    1 -0.302702      1      2  0.414752         1
773         1       1    0 -0.147969      0      0  0.897459         2
774         0       3    0  0.316228      0      0 -0.742269         0

[775 rows x 8 columns]

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
from sklearn.model_selection import train_test_split

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=2026
)

In [40]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
from sklearn.ensemble import RandomForestClassifier

rf_ne_10 = RandomForestClassifier(n_estimators=10)
rf_ne_50 = RandomForestClassifier(n_estimators=50)
rf_ne_100 = RandomForestClassifier(n_estimators=100)
rf_ne_200 = RandomForestClassifier(n_estimators=200)
rf_ne_300 = RandomForestClassifier(n_estimators=300)

In [43]:
rf_ne_10.fit(X_train, y_train)
rf_ne_50.fit(X_train, y_train)
rf_ne_100.fit(X_train, y_train)
rf_ne_200.fit(X_train, y_train)
rf_ne_300.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300)

In [44]:
print(f"Prediction accuracy of n_estimators=10 is {rf_ne_10.score(X_test, y_test)}")
print(f"Prediction accuracy of n_estimators=50 is {rf_ne_50.score(X_test, y_test)}")
print(f"Prediction accuracy of n_estimators=100 is {rf_ne_100.score(X_test, y_test)}")
print(f"Prediction accuracy of n_estimators=200 is {rf_ne_200.score(X_test, y_test)}")
print(f"Prediction accuracy of n_estimators=300 is {rf_ne_300.score(X_test, y_test)}")

Prediction accuracy of n_estimators=10 is 0.8092783505154639
Prediction accuracy of n_estimators=50 is 0.8247422680412371
Prediction accuracy of n_estimators=100 is 0.8350515463917526
Prediction accuracy of n_estimators=200 is 0.8195876288659794
Prediction accuracy of n_estimators=300 is 0.8195876288659794

In [45]:
from sklearn.neighbors import KNeighborsClassifier

knn1 = KNeighborsClassifier(n_neighbors=1)
knn3 = KNeighborsClassifier(n_neighbors=3)
knn5 = KNeighborsClassifier(n_neighbors=5)
knn7 = KNeighborsClassifier(n_neighbors=7)
knn9 = KNeighborsClassifier(n_neighbors=9)

In [46]:
knn1.fit(X_train, y_train)
knn3.fit(X_train, y_train)
knn5.fit(X_train, y_train)
knn7.fit(X_train, y_train)
knn9.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [47]:
print(f"Prediction accuracy of k=1 is {knn1.score(X_test, y_test)}")
print(f"Prediction accuracy of k=3 is {knn3.score(X_test, y_test)}")
print(f"Prediction accuracy of k=5 is {knn5.score(X_test, y_test)}")
print(f"Prediction accuracy of k=7 is {knn7.score(X_test, y_test)}")
print(f"Prediction accuracy of k=9 is {knn9.score(X_test, y_test)}")

Prediction accuracy of k=1 is 0.7474226804123711
Prediction accuracy of k=3 is 0.865979381443299
Prediction accuracy of k=5 is 0.8814432989690721
Prediction accuracy of k=7 is 0.9020618556701031
Prediction accuracy of k=9 is 0.8814432989690721

## 10개의 모델 중 KNN의 k=7이 titanic dataset의 생존 예측 성능이 가장 좋습니다